spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev #开发环境
  application:
    name: levycloud-config-hai-client8201
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: levycloud-config-hai-client8202
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
 